"""update user

Revision ID: 41e79eaae346
Revises: 538c8c6e3e22
Create Date: 2022-09-07 10:53:21.533588

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '41e79eaae346'
down_revision = '538c8c6e3e22'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('create_at', postgresql.TIMESTAMP(), nullable=True))
    op.add_column('user', sa.Column('last_login', postgresql.TIMESTAMP(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_login')
    op.drop_column('user', 'create_at')
    # ### end Alembic commands ###
