"""create permission

Revision ID: 495190226c1c
Revises: 41e79eaae346
Create Date: 2022-09-20 14:26:49.216790

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '495190226c1c'
down_revision = '41e79eaae346'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permission',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('code', sa.VARCHAR(length=64), nullable=False),
    sa.Column('display_name', sa.VARCHAR(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_permission_code'), 'permission', ['code'], unique=False)
    op.create_index(op.f('ix_permission_display_name'), 'permission', ['display_name'], unique=False)
    op.create_index(op.f('ix_permission_id'), 'permission', ['id'], unique=False)
    op.create_table('permission_group',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('permission_id', sa.INTEGER(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['permission_id'], ['permission.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_permission_group_id'), 'permission_group', ['id'], unique=False)
    op.create_index(op.f('ix_permission_group_permission_id'), 'permission_group', ['permission_id'], unique=False)
    op.create_index(op.f('ix_permission_group_user_id'), 'permission_group', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_permission_group_user_id'), table_name='permission_group')
    op.drop_index(op.f('ix_permission_group_permission_id'), table_name='permission_group')
    op.drop_index(op.f('ix_permission_group_id'), table_name='permission_group')
    op.drop_table('permission_group')
    op.drop_index(op.f('ix_permission_id'), table_name='permission')
    op.drop_index(op.f('ix_permission_display_name'), table_name='permission')
    op.drop_index(op.f('ix_permission_code'), table_name='permission')
    op.drop_table('permission')
    # ### end Alembic commands ###
