"""create permission

Revision ID: 51e425d1d8a3
Revises: 495190226c1c
Create Date: 2022-09-20 14:27:36.898450

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51e425d1d8a3'
down_revision = '495190226c1c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
