"""update user

Revision ID: 538c8c6e3e22
Revises: f88706c54055
Create Date: 2022-09-07 10:43:13.013048

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '538c8c6e3e22'
down_revision = 'f88706c54055'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('full_name', sa.VARCHAR(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'full_name')
    # ### end Alembic commands ###
