"""permission be linked

Revision ID: e6043fabd4fd
Revises: 51e425d1d8a3
Create Date: 2022-09-20 14:40:54.597819

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6043fabd4fd'
down_revision = '51e425d1d8a3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_permission',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('permission_id', sa.INTEGER(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('permission_group_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['permission_group_id'], ['permission_group.id'], ),
    sa.ForeignKeyConstraint(['permission_id'], ['permission.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_permission_id'), 'user_permission', ['id'], unique=False)
    op.add_column('permission_group', sa.Column('name', sa.VARCHAR(length=128), nullable=False))
    op.drop_index('ix_permission_group_user_id', table_name='permission_group')
    op.create_index(op.f('ix_permission_group_name'), 'permission_group', ['name'], unique=False)
    op.drop_constraint('permission_group_user_id_fkey', 'permission_group', type_='foreignkey')
    op.drop_column('permission_group', 'user_id')
    op.add_column('user', sa.Column('is_manager', sa.BOOLEAN(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_manager')
    op.add_column('permission_group', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('permission_group_user_id_fkey', 'permission_group', 'user', ['user_id'], ['id'])
    op.drop_index(op.f('ix_permission_group_name'), table_name='permission_group')
    op.create_index('ix_permission_group_user_id', 'permission_group', ['user_id'], unique=False)
    op.drop_column('permission_group', 'name')
    op.drop_index(op.f('ix_user_permission_id'), table_name='user_permission')
    op.drop_table('user_permission')
    # ### end Alembic commands ###
